spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: never
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations:
    - /mappers/*.xml

user:
  profile:
    img:
      default: https://firebasestorage.googleapis.com/v0/b/userprofile-66675.appspot.com/o/user%2Fdefalut.png?alt=media&token=21c67386-8ad9-4855-973d-8e68adcc4958

